### PR TITLE
unfuck alza

### LINKED ISSUE #1417: Alza.cz - nezobrazuje se extenze
na webu Hlídače se produkt napáruje a historii zobrazí, na webu Alzy se extenze ale nezobrazí.
např: https://www.alza.cz/bosch-smv6zdx49e-d6124827.htm

### PR DESCRIPTION
**Pull request by fanick1**
Fix #1417

### CODE REVIEW

**Comment by fanick1** [comment]
Anybody willing to merge this and make a release? @salax / @rarous  / @janfiedler 🥺  ?

**Comment by rarous** [comment]
product images are required

**Comment by fanick1** [comment]
> product images are required

They seem to be completely unused anywhere.

**Comment by fanick1** [comment]
get rid of the imageUrl, srsly

**Comment by rarous** [comment]
Fixed on trunk as it should be. Thank you for your contribution.

**Pull request closed without merging**
