### PR TITLE
fix: pilulka sitemap alternative

### PR DESCRIPTION
**Pull request by JameEnder**
Switched to browsing categories, and added priceWithCode to output as specified by the pilulka issue

### CODE REVIEW

**Comment by JameEnder** [comment]
Not sure where the priceWithCode is supposed to go in the output, so change that as you see fit :)

**Comment by rarous** [comment]
@MartinaGelnerova where should go the `priceWithCode`?

**Comment by rarous** [comment]
@JameEnder please, remove commented out code and Sitemap mentions in doc comments a Sitemap related dead code. Thanks

**Comment by MartinaGelnerova** [comment]
> @MartinaGelnerova where should go the `priceWithCode`?

@rarous @JameEnder currentPrice

**Comment by rarous** [comment]
@JameEnder please, use `priceWithCode` in the chain for the `currentPrice` value, then I'll merge. Thank you

**Comment by JameEnder** [comment]
Updated it, I assumed you want the priceWithCode to take prio over anything else :)

**Comment by rarous** [comment]
Thank you 🙏🏼

**Comment by rarous** [comment]
@MartinaGelnerova try it, please :)

**Comment by MartinaGelnerova** [comment]
built, run => works just fine, thank you!

**Pull request merged**
